### PR TITLE
Changed sales tax base value

### PR DESCRIPTION
**Pull request by ZombieErebus**
Changed max sales tax value to match decrease to 4.5% base

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Hi!

Thanks for you merge request.
Would you please be able to source the changes from CCP please ? I'm vastly out of touch with the game

**Comment by ZombieErebus** [comment]
Hey, not a problem. It was changed somewhat recently, patchnotes are here https://www.eveonline.com/news/view/patch-notes-version-22-01#h2-26 "Marketplace taxes reduced to 4.5%. Down from 8%."

**Comment by Slivo-fr** [comment]
Thanks a lot!

Could you please change the target of the MR to develop ?
I will then merge an look into releasing an update, mipght take some time I didn't do that in a loooooong time 😅

**Comment by ZombieErebus** [comment]
No problem, thanks for responding so quickly given you're not actively maintaining it anymore :D
I'm a bit new to github, hopefully that should be right now :)

**Comment by ZombieErebus** [comment]
I am looking around and can't seem to figure out how to branch from the "develop". I am happy for you to manually change what I've committed and close this request as it may take me a while to figure out how to make a new commit.

Thank you again for responding to this request 😄

**Pull request closed without merging**
