### PR TITLE
Changed sales tax base value

### PR DESCRIPTION
**Pull request by ZombieErebus**
Changed max sales tax value to match decrease to 4.5% base. See #25

### CODE REVIEW

**Comment by Slivo-fr** [comment]
Perfect thank you! 

I'll merge this and try to upload a new release as soon as possible :)

**Comment by Slivo-fr** [comment]
@ZombieErebus could you please try out the beta release and let me know if it works as expected ? 

https://github.com/Slivo-fr/elinor-reloaded/releases/tag/v1.11.0-beta

**Comment by ZombieErebus** [comment]
Yep, works perfectly. Thank you!

**Comment by Slivo-fr** [comment]
Stable update released, thanks for your help!

**Pull request merged**
